//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 01:43:12 PM CST 
//


package platform.nlp.ltp.xml.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LTPParagraph complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LTPParagraph">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sent" type="{}LTPSentence" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LTPParagraph", propOrder = {
    "sent"
})
public class LTPParagraph {

    @XmlElement(required = true)
    protected List<LTPSentence> sent;
    @XmlAttribute
    protected Integer id;

    /**
     * Gets the value of the sent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LTPSentence }
     * 
     * 
     */
    public List<LTPSentence> getSent() {
        if (sent == null) {
            sent = new ArrayList<LTPSentence>();
        }
        return this.sent;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }
    
    /*
     * 获取句子个数
     */
    public int size() {
    	return this.getSent().size();
    }
    
    /*
     * 获取此段的第sent_index句话
     */
    public LTPSentence piece(int sent_index) {
    	try{
    		return this.getSent().get(sent_index);
	    }catch( Exception e ){
			System.out.println("语句"+sent_index+"不存在！");
			e.printStackTrace();
			return null;
		}
	}
    
    /*
     * 获取此段的第sent_index句话的第word_index个单词
     */
    public LTPWord word(int sent_index, int word_index) {
    	try{
    		return this.getSent().get(sent_index).getWord().get(word_index);
	    }catch( Exception e ){
			System.out.println("语句"+sent_index+"的词语"+word_index+"不存在！");
			e.printStackTrace();
			return null;
		}
	}

}
